name: CI

on:
  push:
    branches:
      - master  # запускать при пушах в main ветку
  pull_request:
    branches:
      - master  # запускать при PR в main ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Проверка кода из репозитория

    - name: Set up CMake
      uses: lukka/get-cmake@v3  # Установка CMake

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
